### ISSUE TITLE
Broker field `spec.delivery.retry` is ignored

### ISSUE THREAD

**Issue by norbjd** [knative-sandbox/eventing-natss#334]
**Describe the bug**
When configuring a broker with fields under `spec.delivery` (`retry`, `backoffPolicy`, `backoffDelay`, ...), those fields seems to be ignored. There is no retries if the `Trigger` object fails to deliver successfully the message to the subscriber. In my case, the subscriber is a ksvc, and there is no retries if that ksvc returns an error.

 **Expected behavior**
When configuring a broker with fields under `spec.delivery`, the message should be redelivered (multiple retries) if the receiver (ksvc) returns an error.

 **To Reproduce**
1. Have a fresh Kubernetes cluster with Knative Serving and Eventing installed via YAML files (version 1.4.0).

2. Install components to work with NATS (`natsjsm.yaml`, channel messaging layer `eventing-natss.yaml`, broker layer `mt-channel-broker.yaml`):

```shell
# https://github.com/knative-sandbox/eventing-natss/blob/release-1.4/config/broker/README.md
kubectl apply -f https://raw.githubusercontent.com/knative-sandbox/eventing-natss/knative-v1.4.0/config/broker/natsjsm.yaml

# https://knative.dev/docs/install/yaml-install/eventing/install-eventing-with-yaml/#optional-install-a-default-channel-messaging-layer
kubectl apply -f https://github.com/knative-sandbox/eventing-natss/releases/download/knative-v1.4.0/eventing-natss.yaml

# https://knative.dev/docs/install/yaml-install/eventing/install-eventing-with-yaml/#optional-install-a-broker-layer
kubectl apply -f https://github.com/knative/eventing/releases/download/knative-v1.4.0/mt-channel-broker.yaml
```

3. Use `NatsJetStreamChannel` as default channel:

```shell
kubectl patch configmap/config-br-default-channel \
  --namespace knative-eventing \
  --patch '{"data":{"channel-template-spec": "apiVersion: messaging.knative.dev/v1alpha1\nkind: NatsJetStreamChannel"}}'
```

4. Deploy a simple ksvc (`kn service create error-service --image=myimage --port=8080`) that always return an error 503 to test [handling delivery failure](https://knative.dev/docs/eventing/event-delivery/). The code is the following:

```go
package main

import (
	"log"
	"net/http"
)

func handler(w http.ResponseWriter, req *http.Request) {
	log.Println("It does not work, returning 503")
	http.Error(w, "Does not work", 503)
}

func main() {
	http.HandleFunc("/", handler)
	http.ListenAndServe(":8080", nil)
}
```

5. Create a `Broker`, a `Trigger` pointing to that ksvc, and a `PingSource` to send an event every minute:

```yaml
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default
  namespace: default
  annotations:
    eventing.knative.dev/broker.class: MTChannelBasedBroker
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: config-br-default-channel # NatsJetStreamChannel defined in the ConfigMap
    namespace: knative-eventing
  delivery:
    retry: 5
    backoffPolicy: exponential
    backoffDelay: "PT1S"
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: my-service-trigger
  namespace: default
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: error-service
---
apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: ping
  namespace: default
spec:
  schedule: "* * * * *"
  contentType: "application/json"
  data: '{"msg": "ping"}'
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
```

6. Wait for the logs of `error-service`:

```
2022/05/29 14:22:00 It does not work, returning 503
2022/05/29 14:23:00 It does not work, returning 503
2022/05/29 14:24:00 It does not work, returning 503
```

As you can see, in the logs of the `error-service` pod, there is no sign that the message is send again after an error (there is one log per minute, not 1 + 5 retries as defined in the `Broker` `spec.delivery.retry` field.

 **Knative release version**
v1.4.0

 **Additional context**
I have also tried with NatssChannel (https://github.com/knative-sandbox/eventing-natss/blob/release-1.4/config/broker/README.md#1-nats-streaming-deprecation-notice-) and got the same result.

The docs (https://github.com/knative-sandbox/eventing-natss/blob/knative-v1.4.0/config/README.md#nats-streaming-channels) states:

> If downstream rejects an event, that request is attempted again.

And the knative docs states that Nats Channels does not support any of the `delivery` fields (https://knative.dev/docs/eventing/event-delivery/#channel-support):

![Nats Channel does not support delivery fields](https://user-images.githubusercontent.com/26850303/170869714-b0d99dd3-b104-4a12-a3fe-458a46f3b8dd.png)

So I don't know if this is the normal behavior or if I'm doing something wrong or misunderstanding something.

But what I would like to do is retrying the `PingSource` event if the ksvc returns an error.

Thanks for your help :raised_hands:
