### ISSUE TITLE
broker failed SubscriptionNotMarkedReadyByChannel

### ISSUE THREAD

**Issue by zhaojizhuang** [knative-sandbox/eventing-natss#86]
**Describe the bug**

```shell
[root@k8s-master ~]# kubectl get triggers.eventing.knative.dev
NAME                 BROKER       SUBSCRIBER_URI                                AGE     READY     REASON
testtrigger          testbroker   http://my-service.default.svc.cluster.local   20m     Unknown   SubscriptionNotMarkedReadyByChannel
```
 **To Reproduce**
1. Install Natss streaming
follow steps in `https://github.com/knative-sandbox/eventing-natss/blob/release-0.19/config/broker/README.md`

2. install event-natss
```shell
wget https://github.com/knative-sandbox/eventing-natss/releases/download/v0.19.0/eventing-natss.yaml
kubectl apply -f  eventing-natss.yaml
```
3. create broker and trigger follows e2e step  https://github.com/knative-sandbox/eventing-natss/tree/master/test/e2e/config/direct

```yaml
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: testbroker
  annotations:
    eventing.knative.dev/broker.class: MTChannelBasedBroker
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: config-natss-channel
    namespace: natss
```
trigger
```yaml
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: testtrigger
spec:
  broker: testbroker
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: recorder
```
config-natss-channel

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-natss-channel
  namespace: natss
  labels:
    eventing.knative.dev/release: devel
data:
  channelTemplateSpec: |
    apiVersion: messaging.knative.dev/v1beta1
    kind: NatssChannel
```

 **Knative release version**
v0.19.0

 **Additional context**
Add any other context about the problem here such as proposed priority
